# Generated by Django 5.2.2 on 2025-06-11 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDeporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CicloAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, unique=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('archivado', 'Archivado')], default='activo', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('es_destacado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenGeneralNosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='nosotros/')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MiembroPsicopedagogia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('frase', models.TextField()),
                ('foto', models.ImageField(upload_to='psicopedagogia/')),
            ],
        ),
        migrations.CreateModel(
            name='InstanciaEventoCiclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_formulario', models.URLField(blank=True, null=True)),
                ('ciclco_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instancias_evento', to='psicopedagogia.cicloacademico')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instancias', to='psicopedagogia.evento')),
            ],
        ),
        migrations.CreateModel(
            name='FotoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='galeria_eventos/')),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='psicopedagogia.instanciaeventociclo')),
            ],
        ),
        migrations.CreateModel(
            name='EquipoCopaTecsup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=255)),
                ('foto_equipo', models.ImageField(blank=True, null=True, upload_to='equipos/')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='psicopedagogia.categoriadeporte')),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='psicopedagogia.instanciaeventociclo')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoInscritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='archivos_inscritos/')),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_inscritos', to='psicopedagogia.instanciaeventociclo')),
            ],
        ),
    ]
