# Generated by Django 5.2.2 on 2025-06-11 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psicopedagogia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instanciaeventociclo',
            old_name='ciclco_academico',
            new_name='ciclo_academico',
        ),
    ]
