# Generated by Django 5.2.2 on 2025-06-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicopedagogia', '0002_rename_ciclco_academico_instanciaeventociclo_ciclo_academico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instanciaeventociclo',
            name='link_formulario',
        ),
        migrations.AddField(
            model_name='evento',
            name='link_formulario',
            field=models.URLField(blank=True, null=True),
        ),
    ]
